export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
export const LOGIN_USER_INIT = "LOGIN_USER_INIT"

export const STORE_INIT = "STORE_INIT"