export const GET_JOBS = "GET_JOBS"
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS"
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE"
export const GET_JOBS_INIT = "GET_JOBS_INIT"

export const GET_CANDIDATES = "GET_CANDIDATES"
export const GET_CANDIDATES_SUCCESS = "GET_CANDIDATES_SUCCESS"
export const GET_CANDIDATES_FAILURE = "GET_CANDIDATES_FAILURE"
export const GET_CANDIDATES_INIT = "GET_CANDIDATES_INIT"